# Import necessary components from the agents SDK and dotenv
from agents import Agent, Runner, AsyncOpenAI, set_default_openai_client, set_tracing_disabled, OpenAIChatCompletionsModel
from dotenv import load_dotenv
import os

# Load environment variables from .env file
load_dotenv()

# Retrieve the Gemini API key from environment variables
gemini_api_key = os.getenv("GEMINI_API_KEY")

# Check if the API key is set
if not gemini_api_key:
    print("Error: GEMINI_API_KEY not found in environment variables.")
    print("Please create a .env file in the project root with: GEMINI_API_KEY=your_gemini_api_key_here")
    exit(1)

# Configure the AsyncOpenAI client to point to the Gemini API endpoint
# using the specified base_url and your Gemini API key
external_client = AsyncOpenAI(
  api_key=gemini_api_key,
  base_url="https://generativelanguage.googleapis.com/v1beta/openai/"
)

# Set the default client for the agents SDK
set_default_openai_client(external_client)

# Disable tracing for this
set_tracing_disabled(True)

# Define the model to use (a Gemini model accessible via the OpenAI compatibility layer)
model = OpenAIChatCompletionsModel(
 model = "gemini-2.0-flash", # Example Gemini model
 openai_client = external_client
)

# --- Agent Definition ---

def my_first_agent():
    """
    Defines and runs a simple "Hello World" agent.
    """
    print("--- Running Hello World Agent ---")

    # Define the agent's persona and instructions
    # The instruction tells the agent its goal: to simply say "Hello, world!"
    agent = Agent(
        name="hello_greeter",
        instructions="Your only task is to respond exactly with 'Hello, world!'. Do not say anything else.",
        model=model, 
    )

    # --- Agent Execution ---

    # Run the agent synchronously with a simple trigger prompt.
    # The agent's response is primarily driven by its instruction here.
    # We pass the model explicitly to the run method.
    result = Runner.run_sync(
        agent,
        "Initiate greeting.", # A minimal prompt to trigger the agent
       
    )

    # Print the final output generated by the agent
    
    print(result.final_output)
  

